### ISSUE TITLE
Deleted posts come back

### ISSUE THREAD

**Issue by cinnamon-bun** [sgwilym/earthstar-lobby#1]
To reproduce
* Delete a post, or set its body to `""`.  It immediately vanishes.  
* Sync, and verify it doesn't come back (so far so good)
* Reload the page, and it comes back

Trying to trace what happens when you delete a message:

➟ Delete button calls `set("")`
https://github.com/sgwilym/earthstar-lobby/blob/9bc81246757a20ac8ed57c8c89968dee6069796c/src/Message.tsx#L89

➟ `set` is defined here
https://github.com/sgwilym/earthstar-lobby/blob/9bc81246757a20ac8ed57c8c89968dee6069796c/src/Message.tsx#L40-L63

➟ ? relay and graphql happens

➟ The graphql pub at https://earthstar-graphql-pub.glitch.me/ still contains the original document from before it was zeroed out

**Comment by cinnamon-bun** [comment]
Aha, this might be because of "earthstar-graphql should not return deleted documents by default (changes made)."

Deleted docs serve as tombstones that help remember a deletion has occurred.  They need to be sent in a sync.  They can, however, be omitted in normal queries for UI purposes.

So earthstar-graphql needs to include these when syncing.

I added an issue to the core repo: [Add query field for deleted documents](https://github.com/earthstar-project/earthstar/issues/42)

**Comment by sgwilym** [comment]
Aha! Great catch. I'll add this back in the query for syncing, and add a test too.

**Comment by sgwilym** [comment]
Fixed in v4.1.1 of earthstar-graphql, thanks for this!
