### ISSUE TITLE
A couple of workflow ideas

### ISSUE THREAD

**Issue by cinnamon-bun** [sgwilym/earthstar-lobby#6]
Ideas to make common tasks easier

* Hovering over the workspace name could show the full address as a tooltip (using HTML title attribute), both on the dashboard view and the workspace view.  I happened to make two workspaces with the same prefix and it was hard to tell them apart

* There are some workspace actions that can only be done from the dashboard (copy address, pubs) that would be nice to have in the workspace view also

* The sync button could be always visible since it's such a common action

**Comment by sgwilym** [comment]
Workspace links now have full addresses as tooltips, workspace actions are available everywhere with Earthbar, and live syncing courtesy of Earthstar means no more sync button needed!
