### ISSUE TITLE
Can change anyone's displayNames because paths are missing the "~" for permissions

### ISSUE THREAD

**Issue by cinnamon-bun** [sgwilym/earthstar-lobby#9]
The display-name paths need a tilde like `/about/~${author.address}/name`.  The tilde means only that author can write to that path [(spec)](https://github.com/earthstar-project/earthstar/blob/master/docs/specification.md#write-permissions), otherwise anyone can write there.

While we're changing this, can we also change the path from `name` to `displayName.txt`?

## Where

Writing happens here in lobby:
https://github.com/sgwilym/earthstar-lobby/blob/c747c35205d34c924ed733e327de2fe771808b6a/src/AuthorStatusBit.tsx#L152-L155

Reading seems to happen in graphql
https://github.com/earthstar-project/earthstar-graphql/blob/245eb7d96b2014c60e995a0794977fadf999c5a5/src/util.ts#L119-L121

## Migration

I don't care much about preserving the old names since we have so few users.

If we care, there's 2 approaches
1. If the new-style path is not available, read from the old path as a backup.  Always write to the new path.
2. Migrate data automatically.  This can only happen in the browser-side where the user's credentials are available to sign a new document.

Both ways leave the security hole open (anyone can write to the old style paths) so they should only be deployed for a limited time, or not done at all.

**Comment by cinnamon-bun** [comment]
p.s. right now [Foyer](https://github.com/earthstar-project/earthstar-foyer/) is matching this bug for interoperability.  I'll change it when you change Lobby.

**Comment by sgwilym** [comment]
Thanks for catching this! Display name path was changed to `/about/~name/displayName.txt` in lobby and earthstar-graphql (I also think preserving display names is not a big deal)
